### ISSUE TITLE
Check input types in DataHandle classes

### ISSUE THREAD

**Issue by OliviaLynn** [LSSTDESC/rail_base#47]
We should add explicit type checks to inputs and throw exceptions if they are the wrong type, with an explanation of what’s wrong.

An example of this in GalSim: [link](https://github.com/GalSim-developers/GalSim/blob/3a9ab46b3c11333cc5def004cbce3c74f6f186cf/galsim/gsobject.py#L920C9-L920C9).

This has come up recently with a relatively new user building a pipeline and receiving somewhat cryptic errors. 

I remember goldenspike being broken last October because some package it used had switched to jax arrays over the previous numpy arrays (we had to add the type check [here](https://github.com/LSSTDESC/tables_io/commit/661274717ff1535ac50bfffdc60057b5085efb85)), so it looks like this may continue being a problem if we don't take the time to address it now.

**Comment by aimalz** [comment]
I took the liberty of migrating this issue because we came to the above conclusion at the retreat and just hadn't followed up on it yet. So, this issue can be closed when the requested checks are implemented in the various DataHandle classes.

**Comment by drewoldag** [comment]
So in the interest of being pretty clear. What checks are being discussed here? 

Given the following class hierarchy in [src/rail/core/data.py](https://github.com/LSSTDESC/rail_base/blob/main/src/rail/core/data.py):

- DataHandle
  - TableHandle
    - Hdf5Handle
    - FitsHandle
    - PqHandle
  - QPHandle
  - ModelHandle

I'm assuming that we want to put in new `__init__` methods for the Table, QP, and Model classes that verify that the input is either "table-like", a qp Ensemble, or a model respectively, and return a reasonable error message if not. 

For `QPHandle` it would be something like:
``` 
def __init__(self, tag, data=None, path=None, creator=None): 
    if not isinstance(data, qp.Ensemble):
        logger.error(f"Expected a qp.Ensemble object, but found {}", type(data))
    super().__init__(tag, ...)
```

I'm also assuming that we don't need type checking in the Hdf5, Fits, and Pq classes, because those are just particular containers for "table-like" data. 

Finally, given @eacharles's comment on Aug 1, we would want to introduce a check for an input pandas dataframe for `__call__` as well as updating the docstring. 

I fully recognize that I'm making _a lot_ of assumptions here, so please let me know what all I am incorrect about.

**Comment by eacharles** [comment]
I think just putting in a method cls._validate_data() and calling that in two places in the Base class is enough:
__init__ and set_data()  They we can have the sub-classes implement the _validate_data method.

Problem is that the only class where this is easy is QPHandle.   It all the others it requires some understanding for what the Stage that uses the data expected.   I.e., what kind of model, what kind of table, etc...

**Comment by eacharles** [comment]
to elaborate, you can pretty much hand any pickleable object to the ModelHandle, and that's ok, b/c all it does in pickle it and write it to disk or read it back from disk.

Similarly, you can hand anything that tables_io can write to the particular file format you requested to one of the TableHandles or it's subclasses and that's ok.   You could ask tables_io if it can figure out how to write a particular object to disk in a particular format, but that isn't going to be much help, b/c it can write, say, a numpy.recarray to a parquet file, even if the stage using the data handle doesn't know how to handle it.

**Comment by eacharles** [comment]
Done with #54
